CREATE TABLE IF NOT EXISTS genre(
    id BIGINT NOT NULL AUTO_INCREMENT,
    tmdb_id INT DEFAULT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id)
);